#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# -----> SWIPE GESTURES  <----- #
# ---> 7 Pages Example  <--- #
# -> for T-Watch LoRa <- #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# -> GLOBALS <- #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
globals: 
  - id: start_x
    type: int
    restore_value: no
    initial_value: "0"
  - id: start_y
    type: int
    restore_value: no
    initial_value: "0" 
  - id: current_page
    type: int
    restore_value: no
    initial_value: "0" 

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# -> DISPLAY & TOUCH <- #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
display:
  - platform: ili9xxx
    model: ST7789V
    id: screen
    transform:
      mirror_x: true
      mirror_y: true
      swap_xy: false
    dimensions:
      width: 240
      height: 240
      offset_width: 0
      offset_height: 80
    invert_colors: true
    cs_pin: 12
    dc_pin: 38
    pages:
    
# -> HOME PAGE <- #      
      - id: home_page
        lambda: |-
          it.image(0, 0, id(logo_img));

# -> PAGE 1 <- #
      - id: page1
        lambda: |- 
          it.fill(id(blue));

# -> PAGE 2 <- #
      - id: page2
        lambda: |- 
          it.fill(id(red));

# -> PAGE 3 <- #
      - id: page3
        lambda: |- 
          it.fill(id(blue));

# -> PAGE 4 <- #
      - id: page4
        lambda: |- 
          it.fill(id(red));

# -> PAGE 5 <- #
      - id: page5
        lambda: |- 
          it.fill(id(blue));

# -> PAGE 6 <- #
      - id: page6
        lambda: |- 
          it.fill(id(red));

# -> TOUCHSCREEN <- #
touchscreen:
  - platform: ft63x6
    interrupt_pin: 
      number: GPIO16
      # allow_other_uses: true
    address: 0x38
    display: screen
    id: tscreen
    i2c_id: tsc
    calibration:
      x_min: 0
      x_max: 240
      y_min: 0
      y_max: 240
    
    # -> ON TOUCH <- #  
    on_touch:
      - light.turn_on: 
          id: led
          brightness: 50%


    # -> ON UPDATE <- #
    on_update:
      - lambda: |-
          for (auto touch: touches)  {
            if (touch.state == 1) {
              // Touch started, store initial position
              id(start_x) = touch.x;
              id(start_y) = touch.y;
            } else if (touch.state >= 4) {
              // Touch ended, compare final position to initial
              int dx = touch.x - id(start_x);
              int dy = touch.y - id(start_y);
              if (abs(dx) > abs(dy)) {
                // Horizontal swipe
                if (dx > 0) {
                  // Right swipe
                  if (id(current_page) == 6) {
                    id(screen).show_page(id(page5));
                    id(current_page) = 5;
                  } else if (id(current_page) == 5) {
                    id(screen).show_page(id(page4));
                    id(current_page) = 4;
                  } else if (id(current_page) == 4) {
                    id(screen).show_page(id(page3));
                    id(current_page) = 3;
                  } else if (id(current_page) == 3) {
                    id(screen).show_page(id(page2));
                    id(current_page) = 2;
                  } else if (id(current_page) == 2) {
                    id(screen).show_page(id(page1));
                    id(current_page) = 1;
                  } else if (id(current_page) == 1) {
                    id(screen).show_page(id(home_page));
                    id(current_page) = 0;
                  }
                } else {
                  // Left swipe
                  if (id(current_page) == 0) {
                    id(screen).show_page(id(page1));
                    id(current_page) = 1;
                  } else if (id(current_page) == 1) {
                    id(screen).show_page(id(page2));
                    id(current_page) = 2;
                  } else if (id(current_page) == 2) {
                    id(screen).show_page(id(page3));
                    id(current_page) = 3;
                  } else if (id(current_page) == 3) {
                    id(screen).show_page(id(page4));
                    id(current_page) = 4;
                  } else if (id(current_page) == 4) {
                    id(screen).show_page(id(page5));
                    id(current_page) = 5;
                  } else if (id(current_page) == 5) {
                    id(screen).show_page(id(page6));
                    id(current_page) = 6;
                  }
                }
              }
            }
          }

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# -> BINARY SENSOR <- #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
binary_sensor:  

# -> HOME PAGE <- #
  - platform: touchscreen
    page_id: home_page
    id: home_page_binary
    x_min: 0
    x_max: 240
    y_min: 0
    y_max: 240
    on_double_click:
      min_length: 1ms
      max_length: 700ms
      then: 
        - voice_assistant.start:

# -> PAGE 1 <- #
  - platform: touchscreen
    page_id: page1
    id: page1_binary
    x_min: 0
    x_max: 240
    y_min: 0
    y_max: 240
    on_double_click:
      min_length: 1ms
      max_length: 700ms
      then: 
        - voice_assistant.start:
    on_click:
      min_length: 4000ms
      max_length: 15000ms
      then:
        - switch.turn_on: use_listen_light

# -> PAGE 2 <- #
  - platform: touchscreen
    page_id: page2
    id: page2_binary
    x_min: 0
    x_max: 240
    y_min: 0
    y_max: 240
    on_double_click:
      min_length: 1ms
      max_length: 700ms
      then: 
        - voice_assistant.start:
    on_click:
      min_length: 4000ms
      max_length: 15000ms
      then:
        - switch.turn_on: use_listen_light

# -> PAGE 3 <- #
  - platform: touchscreen
    page_id: page3
    id: page3_binary
    x_min: 0
    x_max: 240
    y_min: 0
    y_max: 240
    on_double_click:
      min_length: 1ms
      max_length: 700ms
      then: 
        - voice_assistant.start:
    on_click:
      min_length: 4000ms
      max_length: 15000ms
      then:
        - switch.turn_on: use_listen_light

# -> PAGE 4 <- #
  - platform: touchscreen
    page_id: page4
    id: page4_binary
    x_min: 0
    x_max: 240
    y_min: 0
    y_max: 240
    on_double_click:
      min_length: 1ms
      max_length: 700ms
      then: 
        - voice_assistant.start:
    on_click:
      min_length: 4000ms
      max_length: 15000ms
      then:
        - switch.turn_on: use_listen_light

# -> PAGE 5 <- #
  - platform: touchscreen
    page_id: page5
    id: page5_binary
    x_min: 0
    x_max: 240
    y_min: 0
    y_max: 240
    on_double_click:
      min_length: 1ms
      max_length: 700ms
      then: 
        - voice_assistant.start:
    on_click:
      min_length: 4000ms
      max_length: 15000ms
      then:
        - switch.turn_on: use_listen_light

# -> PAGE 6 <- #
  - platform: touchscreen
    page_id: page6
    id: page6_binary
    x_min: 0
    x_max: 240
    y_min: 0
    y_max: 240
    on_double_click:
      min_length: 1ms
      max_length: 700ms
      then: 
        - voice_assistant.start:
    on_click:
      min_length: 4000ms
      max_length: 15000ms
      then:
        - switch.turn_on: use_listen_light

